### ISSUE TITLE
Highcharts update and redraw not work

### ISSUE THREAD

**Issue by JasonXDDD** [richardeschloss/nuxt-highcharts#10]
### Version
nuxt-highcharts: ^1.0.3
nuxt: ^2.14.6

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [v] spa

---

This is my highcharts component and set `options` in props.
```vue
<template>
  <div class="widget white-bg shadow p-0 mx-0 my-3">
    <div class="p-3">
      <highchart
        ref="chart"
        :options="options? options: chartOptions"
        :highcharts="hc? hc: highcharts"
        :redraw="true"
        :update="['options', 'options.title', 'options.series']"
      />
    </div>
  </div>
</template>
<script>

export default {
  name: 'AppChart',
  components: {},
  mixins: [MessageService],
  props: ['options', 'hc'], // pass new options and redraw chart
  data: () => {
    return {
      highcharts: Highcharts,
      chartOptions: { ... } // default options
  },
  computed: {},
  watch: {
    options (val, oldval) {
      console.log('change', val) // show change
    }
  }
}
</script>

```

 However, when I pass new options, it doesn't redraw the chart and not any error.

<img width="539" alt="截圖 2020-09-24 下午5 20 57" src="https://user-images.githubusercontent.com/11387364/94126667-792aa000-fe8a-11ea-9527-71c95e026926.png">

How to make the chart redraw when the new options change? Can I call original `chart.reflow()` to hard rerender chart ?

**Comment by richardeschloss** [comment]
Try setting the props' default values to what you have in data. I think it's important to learn the Vue fundamentals, first:

Instead of this:
```js
props: ['options', 'hc'], // pass new options and redraw chart
  data: () => {
    return {
      highcharts: Highcharts,
      chartOptions: { ... } // default options
  },
```

It's better to do this:
```js
props: {
  options: {
    type: Object,
    default() { return /* default chart options */ }
  },
  hc: {
    type: Object,
    default() { return Highcharts }
  }
}
```

Then your template simplifes a lot:

```html
<highchart
        ref="chart"
        :options="options"
        :highcharts="hc"
        :redraw="true"
        :update="['options', 'options.title', 'options.series']"
      />
```

May also want to give your chart a more unique ref if possible? I think "chart" will be too generic and run into naming conflicts.

**Comment by JasonXDDD** [comment]
I think this is not the cause of the problem. I get the error when I change options.
``` 
client.js?06a0:96 TypeError: Cannot read property 'forEach' of undefined
    at eval (highcharts.js?ea7f:373)
    at Array.forEach (<anonymous>)
    at eval (highcharts.js?ea7f:373)
    at f.fireEvent (highcharts.js?ea7f:33)
    at e.bindAxes (highcharts.js?ea7f:372)
    at e.init (highcharts.js?ea7f:370)
    at e.init (highcharts.js?ea7f:455)
    at D.initSeries (highcharts.js?ea7f:310)
    at D.eval (highcharts.js?ea7f:428)
    at f.fireEvent (highcharts.js?ea7f:33)
```

and this is my new options:

```javascript
{
  "chart":{
    "zoomType":"xy"
  },
  "title":{
    "text":"title"
  },
  "xAxis":[
    {
      "categories":[ "104", "105", "106", "107", "108" ],
      "title":{
        "text":"syear"
      }
    }
  ],
  "yAxis":[
    {
      "title":{
        "text":"people"
      }
    },
    {
      "title":{
        "text":"%"
      }
    }
  ],
  "tooltip":{
    "headerFormat":"<span style=\"font-size: 10px\">{point.key}年</span><br/><table>",
    "pointFormat":"<tr><span style=\"color:{point.color}\">●</span> {series.name} - <b>{point.y} 人</b><br/></tr>",
    "footerFormat":"</table>",
    "shared":true,
    "useHTML":true
  },
  "legend":{
    "enabled":true
  },
  "plotOptions":{
    "column":{
      "stacking":"percent"
    }
  },
  "series":[
    {
      "name":"male",
      "type":"column",
      "data":[46,46, 39,38,46 ]
    },
    {
      "name":"female",
      "type":"column",
      "data":[127, 147, 116, 117, 135 ]
    },
    {
      "name":"total",
      "type":"spline",
      "yAxis":1,
      "data":[ 173, 199, 155, 155,181 ]
    }
  ]
}
```

**Comment by richardeschloss** [comment]
The code that handles the redraw is here in the [component](https://github.com/richardeschloss/nuxt-highcharts/blob/5c78373b183ec7c2000a3581b37f23c8362b6a86/highcharts/components.js#L124): 

```js
updateAll(newValue) {
  this.chart.update(newValue, this.redraw, this.oneToOne, this.animation) // this.redraw should be true here (this is the prop)
},
```

If `this.redraw` is true there, then the problem may be with how Vue is observing changes on your options object. I.e., changing just the option's properties should be fine, but providing separate options objects will confuse Vue (and changes will be missed).  

You may also be interested to take a look at this [example](https://github.com/richardeschloss/nuxt-highcharts/blob/5c78373b183ec7c2000a3581b37f23c8362b6a86/components/Chart.vue). 

I personally try to avoid redrawing actually and prefer to just set the data when it changes. I think it goes faster that way.

**Comment by richardeschloss** [comment]
Also, if watching on the `options.series`, the component expects `this.chart.series` to be initialized as an array before changing the series:

This is the watcher for `options.series`:
```js
'options.series'(newValue) {
        if (!newValue) return
        this.chart.series.forEach((s, idx) => {
          s.update(newValue[idx])
        })
      },
```

So, I'm guessing maybe the "forEach" error is on that?
