### ISSUE TITLE
how to refer to the chart instance in script?

### ISSUE THREAD

**Issue by anhln** [richardeschloss/nuxt-highcharts#11]

**Comment by richardeschloss** [comment]
Hi you would use the "ref" attribute in the chart element first, and then your script would access it with "this.$refs[...]" in the same component.

For example:
https://github.com/richardeschloss/nuxt-highcharts/blob/5c78373b183ec7c2000a3581b37f23c8362b6a86/components/SunburstChart.vue#L4

```js
<sunburst :options="chartOptions" ref="sunburst" />
```

Then later, that chart can be referred to with `this.$refs["sunburst"]`
