### ISSUE TITLE
Enhancement: Changing default map from world to Africa (wire up mapChart options?)

### ISSUE THREAD

**Issue by Abdulazeez-Dolapo** [richardeschloss/nuxt-highcharts#13]
Good day. Thanks for your awesome work on this library. I'm sorry if my question sounds lame but I have gone through the docs and I still could not figure it out.

I am trying to change the default map from a world map to an African map and I did this in my `nuxt.config.js` file but it did not work.

`import africaMapData from '@highcharts/map-collection/custom/africa.geo.json'`

 `modules: [
    ['nuxt-highcharts', { mapChart: { mapData: africaMapData } }],
  ]`
 
Can you please point me to the right way to do this.

**Comment by richardeschloss** [comment]
Can you please share your vue page/component ? I'll try to help best I can.

**Comment by Abdulazeez-Dolapo** [comment]
Yes

**Comment by Abdulazeez-Dolapo** [comment]
` <client-only>
      <highmap :options="chartOptions" :mapChart="mapChart" :exporting="true" />
    </client-only>`

**Comment by Abdulazeez-Dolapo** [comment]
Github says I can't send the .vue file format so I'll just paste the code

**Comment by Abdulazeez-Dolapo** [comment]
![Screenshot from 2020-12-02 20-03-18](https://user-images.githubusercontent.com/53010751/100918967-7a56f980-34d9-11eb-8d7f-b48c29994f25.png)

**Comment by Abdulazeez-Dolapo** [comment]
Is there anything else you'll like me to share

**Comment by richardeschloss** [comment]
ok, I'll take a look at it.

**Comment by richardeschloss** [comment]
Can you please clarify "not working". Are you seeing a blank chart or are you seeing the world map data on the chart?

**Comment by richardeschloss** [comment]
Another helpful link is here: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/africa

This we know to be a working example with working chartOptions, please let me know how far you get with this as well.

**Comment by Abdulazeez-Dolapo** [comment]
I'm seeing the world map data on the chart. What I want is to see the Africa map instead.
I'll check out the jsfiddle link. Thank you very much for your time and help.

**Comment by richardeschloss** [comment]
Ok, worldmap data instead of blank chart is better than what I was expecting. You may want to also move the mapChart from a computed prop to data, since I think the mapChart is never changing. Not sure if that will help or not.

**Comment by Abdulazeez-Dolapo** [comment]
Thank you.

**Comment by richardeschloss** [comment]
I hope you get far with this. If there are still problems, I can try to provide a working example later this week, but I think you're on the right track..

**Comment by Abdulazeez-Dolapo** [comment]
I've been able to figure it out. Thank you.

**Comment by richardeschloss** [comment]
Ok. I realized I didn't have mapData wired up. I have a very basic (but unclean) example just pushed to [branch issue/13](https://github.com/richardeschloss/nuxt-highcharts/blob/issue/13/components/AfricaMap.vue)  

It consumes from nuxt config, not yet the prop. I'm not sure how my tests missed that but I'll check later this week.

**Comment by richardeschloss** [comment]
Fully working example pushed. I just need to update the unit tests before releasing.

**Comment by richardeschloss** [comment]
Merged #15
