### ISSUE TITLE
Bug: nuxt doesn't like the conditional requiring :/

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-highcharts#24]
I have a small snippet in the highcharts/components.js that will conditionally use a mock injection which, while isn't completely kosher, makes testing much easier. The workaround is to package the mock just to satisfy Nuxt. A more proper solution may require pulling that code for testing out, and figuring a different way to mock what I need. This bug was introduced in 1.0.6, and a quick fix for users will be to temporarily revert to 1.0.5.

Specifically:
```js
// -- v1.0.6:
const hcProps = {}
const hcModsContext = (!process.env.TEST) 
  // @ts-ignore
  ? require.context('highcharts/modules', true, /\.js$/)
  // @ts-ignore
  : require('../test/mocks').hcModsContext
```

Causes Nuxt to complain: 
"This relative module was not found:  ../test/mocks in ./.nuxt/nuxt-highcharts/components.js"

The conditional expression doesn't provide the protection I thought it would. So the easy fix, but not ideal is to package a dummy mocks just to satisfy the build process:

highcharts/module.js
```js
  ...
  this.addTemplate({ // To be added?
    src: resolve(__dirname, '../test/mocks.js'),
    fileName: 'nuxt-highcharts/test/mocks.js'
  })
  ...
``

**Comment by Bipolar** [comment]
Can you please elaborate on a fix for this? I managed to get it working locally, but it fails on deployment to Vercel.

**Comment by richardeschloss** [comment]
Yeah, the workaround is to just have the dummy mocks.js file in node_modules/nuxt-highcharts/test folder, but it may still fail on Vercel if Vercel nukes the node_modules (i.e., if it doesn't cache after npm installs). 

The quicker fix would be to just revert nuxt-highcharts by one minor version for now. The only feature lost there is the "modules". 

I plan to give this more attention probably next week.

**Comment by richardeschloss** [comment]
Ok, v1.0.7 pushed with the fix.
