### ISSUE TITLE
How can we show noData from no-data-display.js

### ISSUE THREAD

**Issue by swapnilnandgave** [richardeschloss/nuxt-highcharts#31]
### Version
nuxt-highcharts: 
nuxt: 

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 **universal**

**Comment by richardeschloss** [comment]
Use the `modules` prop:

```js
<highchart 
  :modules="['no-data-to-display']" :options="chartOptions" />
```

The support for the companion `noData` options may need to be implemented.

**Comment by swapnilnandgave** [comment]
Great thanks.. It is perfectly working
