### ISSUE TITLE
Hi! How add highchart-more? I want to use a bubble chart. Thx.

### ISSUE THREAD

**Issue by zavodptica** [richardeschloss/nuxt-highcharts#33]

**Comment by richardeschloss** [comment]
Current solution: https://github.com/richardeschloss/nuxt-highcharts/issues/28#issuecomment-812682720

Future solution: planned to be implemented

**Comment by zavodptica** [comment]
> Current solution: [#28 (comment)](https://github.com/richardeschloss/nuxt-highcharts/issues/28#issuecomment-812682720)
> 
> Future solution: planned to be implemented

Thanks for the help. 

But I get an error:
_[Vue warn]: Failed to resolve async component: () => __webpack_require__.e(/*! import()| components/bubble-chart */ "components/bubble-chart").then(__webpack_require__.bind(null, /*!../../components/BubbleChart.vue */ "./components/BubbleChart.vue")).then(c => c.default || c)
Reason: TypeError: Cannot read property 'Core/Chart/Chart.js' of undefined_

[Link to reproduction](https://codesandbox.io/s/frosty-sound-tqu8d?file=/components/BubbleChart.vue)

**Comment by richardeschloss** [comment]
I just added this feature in. It's easy now, using the `more` prop:

`<higchart :options="chartOpts" more />`

That will enable additional charts, including the bubble chart. Working example [here](https://github.com/richardeschloss/nuxt-highcharts/blob/1.0.8/components/BubbleChart.vue)
