### ISSUE TITLE
missingModuleFor: dependencywheel

### ISSUE THREAD

**Issue by zavodptica** [richardeschloss/nuxt-highcharts#44]
Hi @richardeschloss, сould you please help me to fix the error. I am trying to use 'dependency-wheel' diagram. 
But when I reload the page /chart (ctrl + F5) I get the error "missingModuleFor: dependencywheel".
Reproduction - https://codesandbox.io/s/nuxt-highcharts-wisgj?file=/pages/chart.vue

Thank you very much for the help

**Comment by richardeschloss** [comment]
Hi, for 2.x LTS here's a working example:
https://stackblitz.com/edit/nuxt-starter-esom3f?file=components/DependencyWheel.vue

I'm not entirely sure why the "modules" feature isn't working, but it's something I can look into.

**Comment by zavodptica** [comment]
Thanks @richardeschloss
