### ISSUE TITLE
Meteogram problem 

### ISSUE THREAD

**Issue by Ruttanachote** [richardeschloss/nuxt-highcharts#45]
How to use Meteogram chart?
https://www.highcharts.com/demo/combo-meteogram/brand-dark#https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=51.50853&lon=-0.12574&altitude=25

**Comment by richardeschloss** [comment]
You need to use the modules they use: 
```html
<highchart :options="chartOptions" :highcharts="HC" />
```

```js
import HC from 'highcharts'
import WindBarb from 'highcharts/modules/wind-barb'
import PatternFill from 'highcharts/modules/pattern-fill'
export default {
  data() {
    return { HC }
  },
  computed: {
    chartOptions() { /* return chartOptions from their demo */ }
  },
  mounted() {
    WindBart(this.HC)
    PatternFill(this.HC)
  }
}
```

They have an interesting approach to have most of their functionality in their custom class Meteogram. However, taking into account new browser features, such as built-in fetch, and the design of nuxt-highcharts module, it should be far less code for you to write now; simply pick the modules you need (windbarb and pattern-fill) and provide the chart options you want. 

The following should (but doesn't always work with Nuxt 2.x + Highcharts latest). My on-going efforts will be to support Nuxt 3.x plugin
```html
<highchart :options="chartOptions" :modules="['wind-barb', 'pattern-fill']" />
```
