### ISSUE TITLE
Separator lines do not render on highmap

### ISSUE THREAD

**Issue by avpuchkova** [richardeschloss/nuxt-highcharts#47]
Hello! I use nuxt-highcharts and '@highcharts/map-collection/countries/us/custom/us-small.geo.json'
Problem is: separator_lines next to Alaska and to small states do not render

![изображение](https://user-images.githubusercontent.com/80326032/164709553-c238fc2e-7e5b-4db9-a387-57e4d8e22c39.png)

Expected:
![изображение](https://user-images.githubusercontent.com/80326032/164709642-5914a122-5318-417c-be15-e6f6c7ae712e.png)

`<highmap :options="chartOptions" />`
`  import worldMap from '@highcharts/map-collection/countries/us/custom/us-small.geo.json';`

       ` chartOptions: {
          chart: {
            map: worldMap
          },
          credits: {
            enabled: false
          },
          title: {
            text: null
          },
          tooltip: {
            formatter(tooltip) {
              return  `<b>${this.point.name}</b>`
            },
            backgroundColor: '#fff',
            borderColor: '#fff',
            style: {
              fontWeight: 'bold',
              textOutline: 'none',
              fontSize:' 16px'
            },
          },
          legend: {
            enabled: false
          },
          plotOptions: {
            series: {
              events: {
                click: (e) => {
                  let stateCode = e.point.properties['hc-a2'];
                  this.selectedLocation = stateCode;
                  this.selectdLocation()
                }
              }
            }
          },
          series: [{
            name: null,
            borderColor: '#7A8086',
            borderWidth: 0.5,
            allowPointSelect: true,
            states: {
              hover: {
                //color: '#BADA55'
                color: "#2579b7"
              },
              select: {
                enabled: true,
                color: "#2579b7"
              }
            },
          mapNavigation: {
            enabled: true,
            buttonOptions: {
              alignTo: 'spacingBox'
            }
          },
          dataLabels: {
            enabled: true,
            formatter(tooltip) {
              return this.point.properties['hc-a2'];
            },
            color: '#212529',
            verticalAlign: 'middle',
            style: {
              fontWeight: 'normal',
              textOutline: 'none',
            },
          },
          allAreas: true,
          data: codes,
          color: '#C8DDED'
          }]
`
What should I do?

**Comment by richardeschloss** [comment]
Hi I think you're close, but for the map chart, the chartOpts.chart.map is a string identifier, like 'worldMap', and the mapData needs to be passed into the component with the prop (See [props](https://github.com/richardeschloss/nuxt-highcharts#props-extends-and-overrides-module-options) --> map).

`mapData` can either be the json or a string url pointing to the json.

The easiest example to follow would be this one: https://github.com/richardeschloss/nuxt-highcharts/blob/master/components/charts/QuickMods.vue --> this uses the Africa map, but changing the mapData to US should work too.

**Comment by avpuchkova** [comment]
Hello, @richardeschloss ! Thank You for answer. But your example does not work for me. I added new mapchar according you example - result the same, there are not separator lines next to Alaska and lines leading to names of small states

![изображение](https://user-images.githubusercontent.com/80326032/165734211-797ffe33-6686-4eff-8b7c-4d7682c9031b.png)

Expected:
![изображение](https://user-images.githubusercontent.com/80326032/165734556-bc9fe0bd-4673-48b8-b3bc-2bb448403aa4.png)

**Comment by richardeschloss** [comment]
Can you please provide your updated code?

**Comment by richardeschloss** [comment]
Ok, a fix was just released to be compatible with nuxt3. The working example is here: https://github.com/richardeschloss/nuxt-highcharts/blob/feat/v3/components/charts/USMap.vue

This version of nuxt-highcharts can be installed from npm:
> npm i nuxt-highcharts@next

**Comment by avpuchkova** [comment]
@richardeschloss Thank you for answer! But we use Nuxt 2 in our project so nuxt-highcharts 3 does not work at all

**Comment by richardeschloss** [comment]
Nuxt 3 stable release is planned for June 2022, so most of my efforts are going towards that. You might want to update your project to Nuxt3 to get all the benefits...
