### ISSUE TITLE
Nuxt3 Build

### ISSUE THREAD

**Issue by BigEgo** [richardeschloss/nuxt-highcharts#48]
Hello,
I'm using `nuxt-highcharts@next @ 3.0.3` with Nuxt3.
When I run `npm run build`, vite/nitro will not bundle the Highcharts modules. I've tried a lot of configurations and nothing seemed to work. 

Do you have a trick to either have nuxt-highcharts not load uneeded modules or a config to have it bundle in a single file?
Thanks.

Image: built scripts getting loaded. 90+ requests.
![image](https://user-images.githubusercontent.com/1497680/168157729-f7007a76-3636-4245-9f05-7507df3a0140.png)

**Comment by richardeschloss** [comment]
I'm not sure without looking at your config, but I believe for the highcharts modules, you may need to specify `vite.optimizeDeps.include`

**Comment by richardeschloss** [comment]
Closing this one in favor of #49 , which will try to address this issue.
