### ISSUE TITLE
cannot  use Sunburst series type

### ISSUE THREAD

**Issue by JasonXDDD** [richardeschloss/nuxt-highcharts#5]
I want to put this https://www.highcharts.com/demo/sunburst on my component, but it has error:

```
client.js?06a0:96 Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=sunburst
 - missingModuleFor: sunburst
    at D.z (highcharts.js?ea7f:10)
    at f.fireEvent (highcharts.js?ea7f:33)
    at a (highcharts.js?ea7f:11)
    at D.initSeries (highcharts.js?ea7f:310)
    at eval (highcharts.js?ea7f:340)
    at Array.forEach (<anonymous>)
    at D.firstRender (highcharts.js?ea7f:340)
    at D.eval (highcharts.js?ea7f:310)
    at f.fireEvent (highcharts.js?ea7f:33)
    at D.init (highcharts.js?ea7f:309)
```
how can I import this sunburst module to nuxt.config ?

**Comment by richardeschloss** [comment]
I can look into it

**Comment by richardeschloss** [comment]
Ok, you need to import the sunburst module to be able to use it. That's the meaning of the error:

As of today, I think the following should work in your component:
```js
import Highcharts from 'highcharts'
import SunBurst from 'highcharts/modules/sunburst' // should exist in 'node-modules/highcharts/modules/sunburst'

data() {
  return {
    hc: {},  // highcharts instance
    chartOptions: {} // chart options
  }
},
mounted() {
  this.hc = SunBurst(Highcharts) // Add sunburst module 
  this.chartOptions = { ... } // copy the options from your demo link
}
```

Then to use the chart, you would use it in your template:

```html
<template>
  <highchart :options="chartOptions" :highcharts="hc" />
</template>
```

**Comment by richardeschloss** [comment]
Ok, tested two ways. The above snippet works and in addition, I just released 1.0.3 with the sunburst. 

Use in your components like:
```html
<sunburst :options="chartOptions" />
```

Where chart options are like that shown in the demo. A working example is [here](https://github.com/richardeschloss/nuxt-highcharts/blob/master/components/SunburstChart.vue)

**Comment by JasonXDDD** [comment]
Yes, It's work! I draw it finally XD

However, I have the same problem with another chart type. like this:
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fwww.highcharts.com%2Fsamples%2Fhighcharts%2Fdemo%2Fbox-plot%3Fcodepen

I think it need to import all of the part 'More chart types' chart to project in the same way.

![截圖 2020-09-15 下午4 48 43](https://user-images.githubusercontent.com/11387364/93188737-ef851f00-f773-11ea-8248-2d09f44339c8.png)

**Comment by richardeschloss** [comment]
Glad you got it working. When I originally created this, I thought it'd be easier to maintain if I just provide the user with the `<highchart />` component, and then they can provide in any chart variant they want into that:

```js
<highchart :options="chartOptions" :highcharts="hc" />
```

Where "hc" would be the highchart instance. All the charts are there in `highcharts/modules/` and I think it will actually be more flexible that way. For a given `<highchart />` tag, just by changing the "chartOptions" and "hc", even small tweaks, can quickly change the chart. Plus, by sticking with the design, I think the plugin can load faster without the need to scan the highchart modules folder to see what chart modules exist.

**Comment by JasonXDDD** [comment]
I got it, but Highcharts use more than one modules sometimes. like this:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treemap-coloraxis
In this sample, it use `heatmap` and `treemap` modules.
However, I cannot add two module to `this.hc`

``` javascript
import Highcharts from 'highcharts'
import HighchartsTreeMap from 'highcharts/modules/treemap'
import HighchartsHeatMap from 'highcharts/modules/heatmap'
export default {
  mounted () {
    this.hc = HighchartsTreeMap(HighchartsHeatMap(Highcharts)) // not work :(
  }
}
```

**Comment by richardeschloss** [comment]
I don't think it'd be like that. I think you'd want to do something like this: https://codesandbox.io/s/kmm7913zj5?file=/src/app/app.component.ts

```js
import Highcharts from 'highcharts'
import HighchartsTreeMap from 'highcharts/modules/treemap'
import HighchartsHeatMap from 'highcharts/modules/heatmap'

HighchartsHeatMap(Highcharts)
HighchartsTreeMap(Highcharts)

export default {
  mounted () {
    this.hc = Highcharts // works... :)
  }
}
```

Nonetheless, I just opened #9 because I think it may be useful (and perhaps simpler?) if the components just became a single `highchart` component that let the `hc` prop be specifed by either an instance, an array of strings, or string?

Proposal
```html
<!-- sunburst example -->
<highchart :options="chartOpts" hc="sunburst" />  

<!-- instead of: --> 
<sunburst :options="chartOpts" />

<!-- mixed example -->
<highchart :options="chartOpts" hc="['heatmap, 'treemap']" />
```

One tricky thing is they put "exporting" and "fullscreen" in modules, and I consider those to be "features". It would be nice if only chart variants existed in that modules folder.
