### ISSUE TITLE
Resize callback function

### ISSUE THREAD

**Issue by g-tejas** [richardeschloss/nuxt-highcharts#50]
Hey,

I looked through the previous issues, and couldnt find anything related to this, so asking here. 

Versions:
Nuxt RC3
Vue Grid Layout 3.0.0-beta1
Nuxt-highcharts 3.0.7

I was wondering how i would go about, to make nuxt highcharts automatically resize when there is changes to the components in the grid.

The layout looks like this, and the <grid-layout> is reactive. 
```
{"x":0,"y":0,"w":8,"h":14,"i":"0"},
{"x":0,"y":0,"w":8,"h":14,"i":"0"},
{"x":0,"y":0,"w":8,"h":14,"i":"0"},
```
This is what im currently doing, as a workaround, but the website becomes super laggy and its not very smooth.
``` 
setInterval(() => {
  window.dispatchEvent(new Event('resize'));
}, 300);
```

Is there any way i can do this in a more efficient way and any highcharts features that resize automatically when they detect a change in a reactive variable? Thank you so much in advance, you have been extremely helpful in prev issues. Cheers!

**Comment by g-tejas** [comment]
Also, does nuxt-highcharts have support for the Boost modules? https://www.highcharts.com/blog/tutorials/highcharts-high-performance-boost-module/
I have a dashboard of around 4000 points for 10 charts, and its not as fast as I want it to be, so was wonddering if i could use this

**Comment by richardeschloss** [comment]
Perhaps consider using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) ?

**Comment by richardeschloss** [comment]
> Also, does nuxt-highcharts have support for the Boost modules? https://www.highcharts.com/blog/tutorials/highcharts-high-performance-boost-module/ I have a dashboard of around 4000 points for 10 charts, and its not as fast as I want it to be, so was wonddering if i could use this

The `modules` prop is supposed to support all of the highcharts modules, including "boost".

So, the following should load the boost module:
```js
<highchart :options="chartOpts" :modules="['boost']" />
```

Per the article, "By default, all series that can be boosted, will be boosted when simply including the module." so I'm hoping it works.

**Comment by g-tejas** [comment]
As for the boost module, it works, thanks! (Didn't verify w performance testing, but visibly looks better i guess)
For the resize function, the vue grid layout offers a resizeEvent callback function, so I added @resize="updatehighchartsSize" and passed the appropriate parameters in, but I get these errors, which i cant make anything of.

I added these two watchers :update="['options.chart.height', 'options.chart.width']"  to check for any updates to the size. Am i doing anything wrong here on the highcharts side? I can console log the size changes and it works, but problem lies within telling highcharts to take update these changes.
<img width="757" alt="Screenshot 2022-06-12 at 10 12 21 PM" src="https://user-images.githubusercontent.com/76802638/173237376-c99d52d0-4698-4151-9fb0-fb982297acba.png">

**Comment by richardeschloss** [comment]
The nuxt-highcharts calls a few of Highcharts' direct setters (like [`.setTitle`](https://github.com/richardeschloss/nuxt-highcharts/blob/a8226eb679c61f2d5d92f1f19c104936df7110cf/lib/components.js#L158)) but not `.reflow` which is what I think you want. By default, if the specified watchers from the user are not supported by nuxt-highcharts, the library defaults to using [`chart.update`](https://github.com/richardeschloss/nuxt-highcharts/blob/a8226eb679c61f2d5d92f1f19c104936df7110cf/lib/components.js#L182) which should work for most cases. 

Highcharts docs make a note about `.reflow` / resize events with div elements [here](https://api.highcharts.com/class-reference/Highcharts.StockChart#reflow) and provides a clear [example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/chart-reflow/) here which should help you quite a bit.

```html
<highstock .... ref="myChart" />
``` 

```js
this.$refs.myChart.chart.____ // Should have access to the highcharts API, so calling `reflow` here should work
```


Is the naming convention ".client.vue" a new way of client-siding? I thought that only applied to plugins? I thought components needed to be wrapped in `<ClientOnly >` but the naming convention would be useful.

**Comment by richardeschloss** [comment]
Working example pushed here: https://github.com/richardeschloss/nuxt-highcharts/blob/28a84a2375ee8b98310017cfb68acdf9e1a66351/components/charts/BasicChart.vue#L145

In the [feat/resize branch](https://github.com/richardeschloss/nuxt-highcharts/blob/feat/resize/components/charts/BasicChart.vue)

**Comment by g-tejas** [comment]
Thank you so much! One last qn, if I was using vue3 w composition api (typescript), how do i access the $highcharts as well as. the $el, I don't think I can do that.
<img width="654" alt="Screenshot 2022-06-21 at 8 28 12 PM" src="https://user-images.githubusercontent.com/76802638/174799025-7fc20dc8-1686-48e7-a5db-01916aeae7e5.png">

**Comment by g-tejas** [comment]
Hey, thanks for providing so much help. I was able to get the context and an instance of the charts(through chartLoaded) using useNuxtApp() but the problem is that in composition API they declare refs differently, like `let const chart = ref()`. 

It doesn't work (can't access chart instances through ref), when I pass ref="" as a prop in <highchart> and then access it, partly I think because my highchart charts are inside a v-for loop, and it loops through the options (stored in Pinia store) and displays them.

```html
<grid-item v-for="metric in metrics.getVisibleCharts"
        :x="metric.coordinates.x"
        :y="metric.coordinates.y"
        :w="metric.coordinates.w"
        :h="metric.coordinates.h"
        :i="metric.coordinates.i"
        :key="metric.coordinates.i"  
        drag-allow-from=".vue-draggable-handle"
        drag-ignore-from=".no-drag"
    >    
        <v-card elevation="8">              
            <v-sheet class="vue-draggable-handle d-flex justify-space-between pa-1" color="blue-grey-darken-4">
                <v-sheet color="blue-grey-darken-4">
                    <v-icon @click="metrics.disableChart(metric)" end icon="mdi-minus-circle" size="x-small" class="px-0" color="red"/>
                    <v-icon end icon="mdi-circle" size="x-small" color="yellow-darken-3"/>
                    <v-icon end icon="mdi-eye-circle" size="x-small" color="green"/>
                </v-sheet>
                <v-sheet color="blue-grey-darken-4" class="pr-1">
                    <small class="font-weight-thin mr-2">{{ metric.name }}</small>
                    <v-icon :icon="metric.icon" size="x-small" color="grey"/>
                </v-sheet>
                    
            </v-sheet>
            <v-sheet>
                <highstock :options="metric.chartOptions" 
                    :modules="['boost']"
                    class="no-drag"
                    @chartLoaded="chartLoaded"
                />
            </v-sheet>
        </v-card>
    </grid-item>
```

I was able to get an instance of the chart using chartLoaded but the issue is that this instance is only available when it loads and i cant pass it to the resizeObserver.
```ts
const ctx = useNuxtApp();

function chartLoaded(chart) {
    console.log("chart loaded")
    chart.reflow()
    // ctx.$highcharts.components.chart.resizeEvent = resizeEvent;
}
```
