### ISSUE TITLE
Trying to use 'columnrange' 

### ISSUE THREAD

**Issue by ross-hulford** [richardeschloss/nuxt-highcharts#51]
Hi,

I have set more to true.

```
const chartOptions = {
  more: true,
  title: {
    text: 'Solar Employment Growth by Sector, 2010-2016',
  },
```

and in my  series I try and use columnrange
```
series: [
    {
      name: 'Installation',
      type: 'columnrange',
      data: mydata,
    },
  ],
```

but I get

Uncaught (in promise) Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=columnrange
 - missingModuleFor: columnrange

Any ideas why?

Thanks

**Comment by richardeschloss** [comment]
I believe that "columnrange" uses highcharts-more. You can enable that with the `more` prop:

```js
<highchart more :options="chartOptions" />
```

Let me know how it goes.
