### ISSUE TITLE
Updating 2-d series causes browser to hang indefinitely

### ISSUE THREAD

**Issue by mm185376** [richardeschloss/nuxt-highcharts#54]
### Version
nuxt-highcharts: 2.0.4
nuxt: 2.15.8

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt configuration for nuxt-highcharts
```
 modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    'nuxt-highcharts',
  ],
```

### Steps to reproduce
1. Use following code, place under pages directory (i.e. using the default template).
2. Press `add` button
3. Press `add` button
```vue
<template>
  <div>
    <v-btn v-on:click="addSome()">add</v-btn>
    <highchart :options="chartOptions" /><br />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'TraderPage',
  data() {
    return {
      last: 0,
      points: [] as number[][],
    }
  },
  computed: {
    chartOptions() {
      return {
        title: {
          text: 'Chart',
        },
        xAxis: {
          type: 'linear',
          title: {
            text: 'Time',
          },
        },
        legend: {
          enabled: false,
        },
        series: [
          {
            name: 'Some data',
            data: this.$data.points
          },
        ],
      }
    },
  },
  methods: {
    addSome() {
      this.points.push([this.last, this.last])
      this.last = this.last + 1
    },
  },
})
</script>

```

### What is Expected?
2 points added to the chart

### What is actually happening?
1 point is added, after the second click to add button, browser hangs indefinitely with high CPU utilization
![image](https://user-images.githubusercontent.com/66742253/191288472-f803700c-2f40-41e6-a92e-51eb57438b12.png)
![image](https://user-images.githubusercontent.com/66742253/191288804-fb9f086b-92c6-481f-84fc-d4663f44592c.png)

**Comment by richardeschloss** [comment]
And what happens if you try the BasicChart.vue copied in to your components?

**Comment by richardeschloss** [comment]
Ok, those are all concerns with the highcharts API usage and Vue fundamentals, not the original issue. At that point, the underlying libraries deal with that logic. The docs here mention what data types to use: https://www.highcharts.com/docs/advanced-chart-features/boost-module#configuration-data-options .

> In boost mode, [turbo mode](https://api.highcharts.com/highcharts/plotOptions.series.turboThreshold) is always turned on. That means all data points should be configured as an array of numbers (e.g. [1, 2, 3]) or a two dimensional array of numbers (e.g. [ [1, 2], [2, 3], [3, 4] ]).

I am able to use the boost module like this w/o issue: 
```
<highchart :modules="['boost']" ... />
```

How are you using / configuring it?

**Comment by richardeschloss** [comment]
I don't currently have the time right now to look at this but perhaps later tonight. `.push` should work and I agree with you it's preferred to performing a direct copy of the array.

**Comment by richardeschloss** [comment]
Ok, I believe I know what's happening, but I believe it's out of my control. I think when the `series.update` underlying method is called, it may be modifying the data that's given to it, and if it does, it will trigger Vue's watchers to keep firing (so an endless loop).  The way to overcome this is to then disable the watching, but then update the chart as desired. This way you can do the array push instead of array copy.

```html
<highchart ref="chart2D" :options="chartOpts" :update="[]" />
```
Setting `update` to an empty array will disable the watchers. But then the chart updating has to be implemented here: 

```js
methods: {
  append () {
    this.points.push([this.cnt, Math.random() * 10])
    this.$refs.chart2D.chart.series[0].update(this.chartOpts.series[0])
    this.cnt++
  }
}
```

Pushed a working example here: https://github.com/richardeschloss/nuxt-highcharts/blob/feat/v3-rc/components/charts/Data2D.vue
