### ISSUE TITLE
Cannot start nuxt:  Cannot set properties of undefined (setting 'nuxtHighcharts') 

### ISSUE THREAD

**Issue by likymm** [richardeschloss/nuxt-highcharts#55]
Hello, I'm super new in Vue and Nuxt and I want to try to integrate Highchart on my Nuxt 3 project and I just followed the instruction in the docs but I'm getting this issue when I'm running `npm run dev`:

``` 
ERROR  Cannot start nuxt:  Cannot set properties of undefined (setting 'nuxtHighcharts')                     10:55:58  

  at setup (C:/Users/mdajab/nuxt-app/node_modules/nuxt-highcharts/lib/module.js:50:53)
  at normalizedModule (C:/Users/mdajab/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async installModule (/C:/Users/mdajab/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (/C:/Users/mdajab/nuxt-app/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/C:/Users/mdajab/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)                      10:55:56  
  at async Object.invoke (/C:/Users/mdajab/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/C:/Users/mdajab/nuxt-app/node_modules/nuxi/dist/cli.mjs:50:20)
```

### Version
nuxt-highcharts: ^3.0.3
nuxt: 3.0.0

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt configuration for nuxt-highcharts
nuxt.config.ts
```
export default defineNuxtConfig({
  ssr: false,
  modules: [
    '@pinia/nuxt',
    'nuxt-highcharts',
  ],
});
```

### What is Expected?
It should run my application in my local machine

### What is actually happening?
It's showing this error instead: `Cannot start nuxt:  Cannot set properties of undefined (setting 'nuxtHighcharts') `

Please help. Thanks

**Comment by richardeschloss** [comment]
That error is occurring on this line: https://github.com/richardeschloss/nuxt-highcharts/blob/acc983467fe7991b8753380a74ab4e1e6ca863f7/lib/module.js#L53 

The public runtime config should be defined and should be accessible (i.e., `nuxt.options.runtimeConfig.public` should be defined). It works for me when I'm on nuxt-highcharts 3.0.8. What happens if you upgrade?

**Comment by likymm** [comment]
> That error is occurring on this line:
> 
> https://github.com/richardeschloss/nuxt-highcharts/blob/acc983467fe7991b8753380a74ab4e1e6ca863f7/lib/module.js#L53
> 
> The public runtime config should be defined and should be accessible (i.e., `nuxt.options.runtimeConfig.public` should be defined). It works for me when I'm on nuxt-highcharts 3.0.8. What happens if you upgrade?

Works like charrrm! Thanks Man, your best!

I just initially installed it using `npm i nuxt-highcharts@next`.

Upgrading to 3.0.8 solved the issue.

Closing the ticket now. thanks <3

**Comment by richardeschloss** [comment]
Oh thanks for reminding me! The README is out of date, I haven't got around to updating it. I'll update it right now
