### ISSUE TITLE
Feature request: consider supporting all highcharts modules

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-highcharts#9]
### Is your feature request related to a problem? Please describe.

All highcharts modules are in "./node_modules/highcharts/modules/*.js". To use all these modules requires individually importing them and then passing them into the `<highchart />` component as a prop, but may not always work when two modules need to be used together, such as heatmap and treemap. 

Currently, the modules mapChart, stockChart, sunburst and exporting are all coded one by one, where perhaps this code could be dynamic, and auto created based on the modules that exist in that directory.

### Describe the solution you'd like

Consider scanning this directory to build up the list of possible modules so they can easily be used. It may be helpful if this list is attached to the $highcharts property. 

I think it may be helpful if the "hc" property could be either a string or a highcharts instance. If it's a string, look up the module by name 'treemap'. If it's a highchart instance, use that instance.

**Comment by JohnMica** [comment]
would it be easier to provide a prop that could be something like
```
<highchart
    :modules="[ 'xrange','boost' ]"
...
```
and have them automatically imported when requested like this ?

**Comment by richardeschloss** [comment]
Hi, I appreciate the suggestion. I think it could be easier for the user of the library indeed. To take it a step further, we could probably also have an "hcModules" type defined in a "types.d.ts" file so that users get the Intellisense when they are trying to use specific modules.  (Having defined types is something I've been wanting to do for this project anyway, so this would give me a reason to do that)

The code that imports all the hcMods is here: 
https://github.com/richardeschloss/nuxt-highcharts/blob/888143c7dc5b31f01ef76f359ec2fbc8ed1b6f2a/highcharts/components.js#L12

Most of it seems to follow the same form: import module --> provide the init function the HC instance. The only part that deviated was the mapChart, but I think the mapData setting can be done in some separate handler.  

The use of the modules prop will still allow for lazy loading to help with performance.

**Comment by JohnMica** [comment]
from my understanding, the people behind Highcharts do have plans to have the library written in TS, but it may take some time to actually get around to finish that (seems they have tons on their plates).
In the meantime, having a `types.d.ts` could definitely help out

and the hcModules prop sounds more consistent with how you have implemented it so far.

**Comment by richardeschloss** [comment]
I forgot to mention, the highcharts library is currently shipped with type definition files (good news for us because ts or js, we can take advantage of that in our editors)....I updated this repo's [nuxt.config](https://github.com/richardeschloss/nuxt-highcharts/blob/1aacc1d4576d3c3ed5618d6da68a40ac54b3217c/nuxt.config.js#L1) to show what types to key off to get the intellisense / smart suggestions (for suggesting chartOptions, at least; I couldn't quite find a key for "all modules" yet, although each individual module has their interfaces in the "highcharts/modules" folder, so that I may have to just read the directory contents).

**Comment by richardeschloss** [comment]
An [ugly but] working demo was pushed to branch: [feat/modules](https://github.com/richardeschloss/nuxt-highcharts/tree/feat/modules). It's magic trick is to make use of `require.context` to allow lazy loading of the modules. Certain things are not as straightforward as I'd like them to be because the highcharts library has different constructors depending on what module being used (e.g., Highcharts.chart for most charts, but Highcharts.mapChart for the maps. This just requires upkeep on what aliases to use for certain modules)

If you want to give it a whirl, the demo will be at localhost:3000 at "QuickMods" page. The modules get set by the "props" array, with the props simply matching the module name in the folder. This way the following two snippets should produce the same result:

```html
<highchart 
      :modules="['map']"
      :map="mapChart"
      :options="chartOptions" 
      :update="watchers"
    />
 <br>
 Chart above should match the "highmap" below:
 <highmap
    :mapChart="mapChart"
    :options="chartOptions" 
    :update="watchers"
  />
```
Automated testing was working but broke with the introduction of require.context, which will need to be mocked.

Deprecation plan also put into place, should we go forward with this feature.

**Comment by JohnMica** [comment]
this is interesting indeed.

i do get some terminal warnings though

```
 WARN  in ./.nuxt/nuxt-highcharts/components.js                                                                               friendly-errors 09:47:46

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted                   friendly-errors 09:47:46
```

i have a syncExtremes function that zoomes 2 different charts and it seems to be working as well with default line chart.

![Hnet com-image](https://user-images.githubusercontent.com/7076631/101759206-36fc1c80-3ad1-11eb-8a58-1458a895cf60.gif)


not sure i could use this on 2 charts with 
1 chart - `xrange, line, area`
2 chart - `column, bar` or `lollipop` ?


regarding the SSR

- it seems to me that Highcharts is actually just creating the chart as a JS function that will eventually append the SVG but only client-side?

**Comment by richardeschloss** [comment]
I'm afraid highcharts is primarily a client-side library. I'm not entirely sure though, but there have been issues (opened up with highcharts) where the library may depend on the window object (browser) to be able to render the chart to. I'm not entirely sure. I think they are aware of a customer-desire for server-side rendering, I'm just not sure how far along they are with that.

I think the require warning comes during the server-side rendering only? I think require.context is a webpack specific method which is not available server-side?  (I think the reason I haven't seen that warning is my nuxt demo is set to "spa" mode. The plugin could be made to be run client-side only)

It would be nice if things worked in SSR mode too though. but I'd need to spend more time working with the highcharts team. I think to keep this particular feature request scoped, the code currently is close to a "beta" stage, and I'll make note of beta features in the docs, so if people feel daring to try they can. Do you feel like it's close to a beta? 
---
To answer the question about using the chartOptions on 2 charts, it should still work, as long as the chartOptions are structured exactly the way highcharts expects (highcharts doesn't really provide much warning or error messages if the chartOptions are off, even by a little bit; it's tough to do that). It can also be dependent on how those individual options (i.e., xrange) are edited and tied back into chartOptions (in which case, it could be more of an issue with javascript and reactivity fundamentals)

**Comment by JohnMica** [comment]
i'de forked the feature branch and started with a nuxt-ts from scratch https://github.com/JohnMica/nuxt-ts-nuxt-highcharts 
- i got stuff working with Nuxt TS
- it builds (static, SSR) and serves this as intended
- just thought the latest of everything in libs could be a good thing

should i create a PR to yours ?

**Comment by richardeschloss** [comment]
Sure, a PR would be great and much appreciated! That would make it easier for me to compare the code changes.

**Comment by richardeschloss** [comment]
@JohnMica It just occurred to me that even with the changes, I'm not sure if the users of the library would get those changes, just because of the project folder structure. I.e., when someone does "npm install nuxt-highcharts", the library will install to "node_modules". 

So, the question I have is, if someone didn't have the nuxt-typescript build in their workspace, would the proposed change work for them? Or would they have to set up their [project root]/package.json file with the project dependencies you have in your repo? If so, it may be necessary for us to update the README.md with the instructions on what to install (even if it's simply "npm i -D @nuxt/typescript-build"). And if you think there's any specific things users might need in their tsconfig.json, that may be helpful too.

**Comment by JohnMica** [comment]
- the required devdep and dep include the TS requirements
- there is a tsconfig.json file as well
- initial release for the TS branch would need to be updated once Nuxt goes into v3
- then we could perhaps think of a better way to improve this module ?

**Comment by richardeschloss** [comment]
Hi John, 

I appreciate the work you've done on this. I'll review the PR now.

Rich

**Comment by richardeschloss** [comment]
Also, just as a heads up, I recently am in the process of starting a new full-time role, and my time on this project may get reduced, but I'll try to be responsive.

**Comment by JohnMica** [comment]
good luck with your new job @richardeschloss 
hopefully, with community help we could get this module a better traction and still keep it relevant?

**Comment by richardeschloss** [comment]
Hi John, thanks for the PR. I'll take a look at it later today. 

I think clearly defined and scoped issues*, and with proper labels, help this module pretty much sustain itself. Assigning a task to an individual who may have the most interest in it (usually the person who brought up the issue), may put the most effort into closing the issue. I think most people who present an issue want to have a chance at solving their problem before giving up at it, and will want to showcase their talents. By assigning tasks to individuals, they get the opportunity to try, and they are motivated to try harder when the project has high visibility. I can't speak for others, but I know whenever I present an issue on someone else's project, at the same time I hope to have a PR ready to be paired with that issue.

Hopefully, as more people get involved, the SLDC become simpler. The CI / CD system will show people right away if their submission works or doesn't at the time of the PR, and if it does, it's just me clicking the merge button. 

* to address ways to improve this module...
  * generally-speaking, I think the module is most helpful when it's simply used to wire up the highcharts library underneath. So, one install, and it's easy to just start using, with the config in Nuxt closely matching the highcharts API as best as possible. It's pretty close to that today. Since highcharts is always changing, this module is easiest to maintain when we reuse their types wherever possible.
  * specifically-speaking, highcharts also ships with themes, indicators, gfx (like stock icons), es-modules (which seems like they're trying to migrate from "modules" to this?), css (highcharts styles). For this, current users of this module have to individually import that stuff. This stuff could probably be auto-imported, but everything has trade-offs...auto-import will come with a small time cost affecting the boot time of the app. 
  * phase out the items marked for deprecation, since the modules prop is now in there.
  * improved documentation, perhaps using nuxt-content. The demos would go in the docs. My experience is that the nuxt-content docs are much more useful than the github README.md when the project grows.
  * try to keep this module lightweight (ideally, most of the weight is in the highcharts library, this module should just be thought of as the glue between that and the Nuxt app, in my opinion)
  * perhaps leverage nuxt-pwa (but I think might be for the app scope, not this one?). I think nuxt-pwa could help with caching of assets and chartOptions. 
  * typescript-first or javascript-first? I'm not sure. It seems like highcharts is going the typescript-first route, even though they've been on javascript forever. most of their code is shifting to typescript, in which case, your code on the feat/ts may be very helpful.  The module currently has 3.8k downloads, and we just need to be mindful of the users who may be working javascript-first.

**Comment by richardeschloss** [comment]
Some discussion moved to #21 to help keep this issue scoped and focused to "feat/modules".

**Comment by richardeschloss** [comment]
> * the required devdep and dep include the TS requirements
> * there is a tsconfig.json file as well
> * initial release for the TS branch would need to be updated once Nuxt goes into v3
> * then we could perhaps think of a better way to improve this module ? 
--> Discussed in greater detail in #21.

**Comment by richardeschloss** [comment]
Closing. Added feat/modules in #22
